### ISSUE TITLE
Established CSGO connection, getting rank information & Killed bug 

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/CSGO-Overwatch-Bot#127] opened 2020-09-12 16:20 UTC
Hello after the new update (2.2.0)
1.First bug [Established CSGO connection, getting rank information(after re-entering cs go it was updated)] rare < !!!
2. if you receive a demo larger than 100 mb, Killed tested on a VPS (4 gb ram) and on Pc (8 bg ram) with the same demo 100% when unzipping
![InkedScreenshot_3_LI](https://user-images.githubusercontent.com/45514952/92999848-e6eed780-f52c-11ea-91c6-c9d9f8be7dad.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/45514952/92999849-e8200480-f52c-11ea-8c1d-fd1c0cc6648a.png)
![weqwe](https://user-images.githubusercontent.com/45514952/92999875-4b119b80-f52d-11ea-8b62-5ecbfbd4a759.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/45514952/92999851-e8b89b00-f52c-11ea-9ff2-8587be5f9e29.png)
vps speedtest
![Screenshot_4](https://user-images.githubusercontent.com/45514952/92999852-ea825e80-f52c-11ea-8aba-2995adaacf4b.png)

**Comment by BeepIsla** [comment] 2020-09-12 16:21
Can you post the demolink here?

**Comment by xSuspect** [comment] 2020-09-12 16:23
> 1. Are you using invisible option in the console or not?
invisible 
> 2. Can you post the demolink here?
http://replay138.valve.net/730/003435671316483539268_1775591554.dem.bz2

**Comment by BeepIsla** [comment] 2020-09-12 16:32
What branch are you using? Worker or Master?

**Comment by xSuspect** [comment] 2020-09-12 16:36
> What branch are you using? Worker or Master?
Worker 
I found another bug
after I did that 100 mb demo manually, the uramator refuses to download forgetful in time [I have reporters twice]
![Screenshot_1](https://user-images.githubusercontent.com/45514952/93000165-31715380-f52f-11ea-8c19-5e2a4dbd3334.png)
![Screenshot_2](https://user-images.githubusercontent.com/45514952/93000167-3209ea00-f52f-11ea-9d8e-a98f7e43e33a.png)

**Comment by BeepIsla** [comment] 2020-09-12 16:38
> I found another bug

Perfect World heavily limits download rate, this is not a bug, just wait.

**Comment by xSuspect** [comment] 2020-09-12 16:40
> > I found another bug
> 
> Perfect World heavily limits download rate, this is not a bug, just wait.
>  Can't you put a message, something?
> What NodeJS version are you using?

v12.18.3

**Comment by BeepIsla** [comment] 2020-09-15 01:18
`Killed` seems to always come from NodeJS running out of memory which is weird with a 4GB ram machine. The `Killed` part seems to specifically happen when parsing starts, so when the Worker process is booting up and getting ready to parse the demo. Maybe the worker process has stricter resource limits? But it wouldn't end the whole process, just emit an error. This is a little odd.

**Comment by ZAp220** [comment] 2020-09-15 09:43
I have been using overwatch bot since last week, i have done 560 cases so far , it works properly for me , since i started to use the previous version of it.

**Comment by BeepIsla** [comment] 2020-09-20 16:38
@xSuspect If you can try the [`worker` branch](https://github.com/BeepIsla/CSGO-Overwatch-Bot/tree/worker) again, it has been updated to include all of the latest changes from `master` and some more. Maybe it helps with memory usage?

**Comment by liebeskummer** [comment] 2020-09-21 20:58
Any bans yet?

**Comment by ZAp220** [comment] 2020-09-22 00:44
i didn't get banned , it works properly..

**Comment by BeepIsla** [comment] 2020-09-22 11:40
Do not hijack other peoples issues, make your own. Alternatively just read the very top of the README.

To answer your question: Yes. Someone got all of their accounts manually suspended roughly a year or two ago for botting Overwatch cases. Not bans or suspensions I know of ever since.

**Comment by BeepIsla** [comment] 2020-09-22 17:03
Closing this in favor of #139 because it is a bit more organized.

**Closed by BeepIsla** 2020-09-22 17:03 UTC
Labels: bug, help wanted
